name: PKGBUILD CI

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
        - name: Makepkg Build and Check (Unmaintained)
          uses: edlanglois/pkgbuild-action@v1.1.9
